### PR TITLE
Increase WGET retry number for Spark dowload

### PR DESCRIPTION
**Pull request by bzz**
2 -> 5 to avoid CI failures

### CODE REVIEW

**Comment by 1ambda** [comment]
@bzz Thanks!

**Comment by bzz** [comment]
It looks like it did not help https://travis-ci.org/bzz/incubator-zeppelin/jobs/179696441

```
[ERROR] Failed to execute goal com.googlecode.maven-download-plugin:download-maven-plugin:1.3.0:wget (download-pyspark-files) on project zeppelin-spark-dependencies_2.11: IO Error: Could not get content -> [Help 1]
```

Hm..

**Comment by bzz** [comment]
@1ambda a strange guess - as this is already merged, to save some time, could you try yourself on apache/zeppelin#1689 to change version of https://github.com/maven-download-plugin/maven-download-plugin back to `1.2.1` ?

**Comment by 1ambda** [comment]
@bzz I will rollback to 1.2.1

**Pull request merged**
